In [121]:
import pandas as pd

In [122]:
df = pd.read_csv('results/pu_classify_results_Cora.csv')
# df = pd.read_csv('results/pu_classify_results_CiteSeer.csv')

In [123]:
df.columns

Index(['Unnamed: 0', 'acc', 'f1', 'precision', 'recall', '1/1', '0/0', '0/1',
       '1/0', 'model', 'dataset', 'rate', 'length negatives',
       'length positives'],
      dtype='object')

In [124]:
import pandas as pd

# Supondo que seu dataframe seja df
df_grouped = df.groupby(['rate', 'model'])[['acc', 'f1']].mean().reset_index()

In [125]:
df_grouped[df_grouped['rate'] == 0.01]

    rate        model       acc        f1
0   0.01        CCRNE  0.700000  0.000000
1   0.01  DropEdgeGCN  0.702467  0.246667
2   0.01          GAT  0.654067  0.304333
3   0.01          GCN  0.659867  0.187633
4   0.01    GraphSage  0.715300  0.348033
5   0.01       LP_PUL  0.738167  0.258900
6   0.01         MCLS  0.327633  0.452033
7   0.01        PU_LP  0.747167  0.306300
8   0.01        RCSVM  0.700000  0.000000
9   0.01         RGAT  0.735567  0.441367
10  0.01         RGCN  0.758767  0.496567
11  0.01   RGraphSage  0.781233  0.542267

In [126]:
df_grouped[df_grouped['rate'] == 0.05]

    rate        model       acc        f1
12  0.05        CCRNE  0.713367  0.199333
13  0.05  DropEdgeGCN  0.795500  0.510733
14  0.05          GAT  0.824967  0.618100
15  0.05          GCN  0.747500  0.274033
16  0.05    GraphSage  0.849933  0.688533
17  0.05       LP_PUL  0.773333  0.404733
18  0.05         MCLS  0.322333  0.446833
19  0.05        PU_LP  0.773867  0.439700
20  0.05        RCSVM  0.708533  0.000867
21  0.05         RGAT  0.850933  0.701300
22  0.05         RGCN  0.851333  0.688100
23  0.05   RGraphSage  0.849967  0.707000

In [127]:
df_grouped[df_grouped['rate'] == 0.1]

    rate        model       acc        f1
24   0.1        CCRNE  0.747367  0.447167
25   0.1  DropEdgeGCN  0.812467  0.493933
26   0.1          GAT  0.853567  0.670600
27   0.1          GCN  0.756767  0.242300
28   0.1    GraphSage  0.852700  0.661233
29   0.1       LP_PUL  0.795833  0.483700
30   0.1         MCLS  0.296300  0.432433
31   0.1        PU_LP  0.807000  0.537267
32   0.1        RCSVM  0.719867  0.002700
33   0.1         RGAT  0.839367  0.629067
34   0.1         RGCN  0.834533  0.605467
35   0.1   RGraphSage  0.829067  0.609067

In [128]:
df_grouped[df_grouped['rate'] == 0.15]

    rate        model       acc        f1
36  0.15        CCRNE  0.781633  0.515300
37  0.15  DropEdgeGCN  0.806167  0.471600
38  0.15          GAT  0.841033  0.603300
39  0.15          GCN  0.798033  0.409700
40  0.15    GraphSage  0.854700  0.658300
41  0.15       LP_PUL  0.808567  0.461933
42  0.15         MCLS  0.304867  0.424367
43  0.15        PU_LP  0.821100  0.525667
44  0.15        RCSVM  0.731267  0.002867
45  0.15         RGAT  0.832567  0.562133
46  0.15         RGCN  0.860133  0.671667
47  0.15   RGraphSage  0.834467  0.574700

In [129]:
df_grouped[df_grouped['rate'] == 0.2]

    rate        model       acc        f1
48   0.2        CCRNE  0.776933  0.534167
49   0.2  DropEdgeGCN  0.804733  0.410533
50   0.2          GAT  0.844667  0.588733
51   0.2          GCN  0.811933  0.444800
52   0.2    GraphSage  0.840067  0.575033
53   0.2       LP_PUL  0.801700  0.388133
54   0.2         MCLS  0.306333  0.395633
55   0.2        PU_LP  0.811667  0.440233
56   0.2        RCSVM  0.743400  0.006100
57   0.2         RGAT  0.836400  0.543433
58   0.2         RGCN  0.852767  0.623533
59   0.2   RGraphSage  0.851867  0.611600

In [130]:
df_grouped[df_grouped['rate'] == 0.25]

    rate        model       acc        f1
60  0.25        CCRNE  0.823767  0.582367
61  0.25  DropEdgeGCN  0.824300  0.485600
62  0.25          GAT  0.874333  0.695500
63  0.25          GCN  0.827333  0.492367
64  0.25    GraphSage  0.864733  0.668567
65  0.25       LP_PUL  0.839467  0.531533
66  0.25         MCLS  0.464433  0.465200
67  0.25        PU_LP  0.851433  0.599667
68  0.25        RCSVM  0.756533  0.015067
69  0.25         RGAT  0.874067  0.679800
70  0.25         RGCN  0.857400  0.608533
71  0.25   RGraphSage  0.863133  0.640067