In [11]:
import pandas as pd

In [12]:
# df = pd.read_csv('results/pu_classify_results_Cora.csv')
# df = pd.read_csv('results/pu_classify_results_CiteSeer.csv')
# df = pd.read_csv('results/neg_inf_results_Cora.csv')
df = pd.read_csv('results/neg_inf_results_CiteSeer.csv')

In [13]:
df.columns

Index(['Unnamed: 0', 'acc', 'f1', 'precision', 'recall', '1/1', '0/0', '0/1',
       '1/0', 'model', 'dataset', 'rate', 'length negatives',
       'length positives'],
      dtype='object')

In [14]:
import pandas as pd

# Supondo que seu dataframe seja df
df_grouped = df.groupby(['rate', 'model'])[['acc', 'f1']].mean().reset_index()

In [15]:
df_grouped[df_grouped['rate'] == 0.01]

   rate        model      acc       f1
0  0.01  DropEdgeGCN  0.79998  0.88728
1  0.01         RGCN  0.83330  0.90910
2  0.01  SkipNodeGCN  0.90000  0.94182

In [16]:
df_grouped[df_grouped['rate'] == 0.05]

   rate        model      acc       f1
3  0.05  DropEdgeGCN  0.90304  0.94880
4  0.05         RGCN  0.96364  0.98144
5  0.05  SkipNodeGCN  0.94546  0.97154

In [17]:
df_grouped[df_grouped['rate'] == 0.1]

   rate        model      acc       f1
6   0.1  DropEdgeGCN  0.94544  0.97190
7   0.1         RGCN  0.96058  0.97984
8   0.1  SkipNodeGCN  0.90908  0.95198

In [18]:
df_grouped[df_grouped['rate'] == 0.15]

    rate        model    acc       f1
9   0.15  DropEdgeGCN  0.944  0.97116
10  0.15         RGCN  0.954  0.97626
11  0.15  SkipNodeGCN  0.922  0.95902

In [19]:
df_grouped[df_grouped['rate'] == 0.2]

    rate        model      acc       f1
12   0.2  DropEdgeGCN  0.95486  0.97684
13   0.2         RGCN  0.97592  0.98778
14   0.2  SkipNodeGCN  0.94436  0.97120

In [20]:
df_grouped[df_grouped['rate'] == 0.25]

    rate        model     acc       f1
15  0.25  DropEdgeGCN  0.9509  0.97482
16  0.25         RGCN  0.9533  0.97606
17  0.25  SkipNodeGCN  0.9365  0.96706