In [21]:
import pandas as pd

In [22]:
# df = pd.read_csv('results/pu_classify_results_Cora.csv')
# df = pd.read_csv('results/pu_classify_results_CiteSeer.csv')
# df = pd.read_csv('results/neg_inf_results_Cora.csv')
df = pd.read_csv('results/pu_classify_results_Cora.csv')

In [23]:
df.columns

Index(['Unnamed: 0', 'acc', 'f1', 'precision', 'recall', '1/1', '0/0', '0/1',
       '1/0', 'model', 'dataset', 'rate', 'length negatives',
       'length positives'],
      dtype='object')

In [24]:
import pandas as pd

# Supondo que seu dataframe seja df
# df_grouped = df.groupby(['rate', 'model'])[['acc', 'f1']].mean().reset_index()

df_grouped = df.groupby(['rate', 'model'])['f1'].agg(
    f1='mean',
    f1_std='std'
).reset_index()

In [34]:
df_grouped[df_grouped['model'] =='RGCN']

    rate model       f1    f1_std
5   0.01  RGCN  0.52206  0.205365
13  0.05  RGCN  0.71028  0.036655
21  0.10  RGCN  0.70780  0.059145
29  0.15  RGCN  0.69156  0.033567
37  0.20  RGCN  0.69090  0.066940
45  0.25  RGCN  0.74080  0.011765

In [26]:
df_grouped[df_grouped['rate'] == 0.05]

    rate        model       f1    f1_std
8   0.05  DropEdgeGCN  0.63770  0.089003
9   0.05          GAT  0.70648  0.062147
10  0.05          GCN  0.63396  0.195756
11  0.05    GraphSage  0.71234  0.066860
12  0.05         RGAT  0.68770  0.040588
13  0.05         RGCN  0.71028  0.036655
14  0.05   RGraphSage  0.68986  0.020419
15  0.05  SkipNodeGCN  0.43940  0.024688

In [27]:
df_grouped[df_grouped['rate'] == 0.1]

    rate        model       f1    f1_std
16   0.1  DropEdgeGCN  0.73232  0.023481
17   0.1          GAT  0.68334  0.078915
18   0.1          GCN  0.67862  0.035674
19   0.1    GraphSage  0.67790  0.059588
20   0.1         RGAT  0.69378  0.047389
21   0.1         RGCN  0.70780  0.059145
22   0.1   RGraphSage  0.70186  0.070843
23   0.1  SkipNodeGCN  0.41262  0.031280

In [28]:
df_grouped[df_grouped['rate'] == 0.15]

    rate        model       f1    f1_std
24  0.15  DropEdgeGCN  0.69834  0.036390
25  0.15          GAT  0.66350  0.096677
26  0.15          GCN  0.67550  0.087245
27  0.15    GraphSage  0.64812  0.042149
28  0.15         RGAT  0.66644  0.083328
29  0.15         RGCN  0.69156  0.033567
30  0.15   RGraphSage  0.72378  0.033058
31  0.15  SkipNodeGCN  0.36162  0.027501

In [29]:
df_grouped[df_grouped['rate'] == 0.2]

    rate        model       f1    f1_std
32   0.2  DropEdgeGCN  0.68254  0.052781
33   0.2          GAT  0.69842  0.056731
34   0.2          GCN  0.66668  0.044976
35   0.2    GraphSage  0.73362  0.026401
36   0.2         RGAT  0.71498  0.024747
37   0.2         RGCN  0.69090  0.066940
38   0.2   RGraphSage  0.74012  0.007867
39   0.2  SkipNodeGCN  0.37842  0.036421

In [30]:
df_grouped[df_grouped['rate'] == 0.25]

    rate        model       f1    f1_std
40  0.25  DropEdgeGCN  0.61976  0.066600
41  0.25          GAT  0.66814  0.021967
42  0.25          GCN  0.65762  0.059104
43  0.25    GraphSage  0.68408  0.049483
44  0.25         RGAT  0.70196  0.056989
45  0.25         RGCN  0.74080  0.011765
46  0.25   RGraphSage  0.73500  0.054842
47  0.25  SkipNodeGCN  0.36518  0.053226